version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./src/:/code/
    ports:
      - 8000:8000


networks:
  default:
    name: fastfish_default
    external: true
